Feature/schedule form
HUHS-ReactStudy/huhs-reservation-frontend pull request #4
Opened 2022-05-30 12:06 UTC by KIMMIKSIK

## 세부 사항
- HUHS캘린더의 신청폼 기초 틀 제작

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x]  코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-06-01 11:28 UTC, KimGaeun0806 commented on src/components/secondContentBox.jsx
> +        <StartEndDate type="datetime-local" placeholder="2022년 5월 16일(월) 오후 05:30" />
이부분 placeholder에는 그냥 예시로 아무 날짜 아무 시간이나 적어놓는걸까요?

2022-06-01 15:31 UTC, KIMMIKSIK commented on src/components/secondContentBox.jsx
> +        <StartEndDate type="datetime-local" placeholder="2022년 5월 16일(월) 오후 05:30" />
이 부분은 다른 분들과도 얘기가 좀 필요할 것 같아요! 디자인에는 그냥 저렇게 날짜를 적으시긴 했는데 초기화면에 디폴트 날짜를 설정해야할지 아니면 0000년 00월 00일 이런 식으로라도 표현을 해야할지 의견을 나눠봐야겠네요! 좋은 리뷰 감사드려요!

2022-06-01 15:43 UTC, wjdgml3834 requested changes
색깔을 useState를 통해서 저장하고 사용하는 방식이 정말 인상적이었습니다 :) 많이 배웠습니다.
가급적이면 회의 때 말씀드린 것 처럼 components안에 들어가는 파일 이름은 대문자로 서로 통일해주시면
감사하겠습니다. 
또한 작명시에 firstContentBox, secondContentBox 이런식으로 넘버링을 하는것보다 어떤 컴포넌트인지 알 수 있도록 작명하시면 더 명확해질 듯 합니다.

2022-06-01 15:43 UTC, chilldata commented on .eslintrc.js
> +    'no-unused-vars': 'warn',
회의때 같이 얘기 나눈 것 처럼 배포할 때, 문제가 발생할 수 있기 때문에 no-unused-vars는 'warn'도 좋지만 아예 eslint쪽에서
에러를 잡아줄 수 있도록 해주시는것이 좋겠습니다 :) 
위의 코드는 rules에서 통일되도록 제외시켜주시면 감사하겠습니다.

2022-06-01 15:43 UTC, wjdgml3834 commented on package.json
> +    "eslint-plugin-prettier": "^4.0.0",
eslint-plugin-prettier를 설치하신 이유가 궁금합니다!!
혹시 eslint-config-prettier를 하셨음에도 어떤 오류를 경험하셨을까요?
제가 eslint-plugin-prettier는 포맷팅 문제도 오류로 출력되어서 오류 메시지가 지나치게 많아지며 느리기 때문에
가급적 사용하지 말라는 글을 본적이 있어서 궁금해서 여쭤봅니다. :)
[eslint-config-prettier와 eslint-plugin-prettier](https://yrnana.dev/post/2021-03-21-prettier-eslint)

2022-06-01 15:43 UTC, chilldata commented on src/components/secondContentBox.jsx
> +  font-size: 16px;
혹시 font-family: 'Noto Sans KR'을 계속해서 써주신 이유가 궁금합니다!
혹시 GlobalStyle에서 제가 기본 폰트로 설정을 해두었는데 input 요소에는 잘 적용이 안되었는지요?
만약에 안되었으면 제가 GlobalStyle을 조금 더 수정해야할 듯합니다.

2022-06-01 15:43 UTC, wjdgml3834 commented on src/components/firstContentBox.jsx
> +`;
제가 이 부분에 대해서 잘 모르겠어서 혹시 간단히라도 설명해주시면 감사하겠습니다.
(너무 길다 싶으면 회의 때 설명하셔도 됩니다 ^^)

2022-06-01 15:43 UTC, wjdgml3834 commented on src/components/thirdContentBox.jsx
> +          <Input placeholder="학번을 입력해주세요" />
혹시 앞으로 styled-components를 사용하여 이름 지어주실때 그냥 Input으로 써주는것 보다는 조금 길더라도 어떤 input인지 알 수 있게 써주시는 건 어떨지 제안드립니다!

2022-06-01 16:26 UTC, KIMMIKSIK commented on .eslintrc.js
> +    'no-unused-vars': 'warn',
좋은 리뷰들 감사드립니다!! 이번에 처음 디자인을 보며 작업을 하다보니 여러모로 부족함을 많이 느꼈습니다. 다시 디자인 보면서 맞춰서 작업하고 있으니 이번 pr건은 merge하지 않는것으로 우선 부탁드립니다. 본론으로 돌아와서 말씀드리면  no-unused-vars는 제가 지난 월요일날 말씀드렸던 definition for rule 'prettier/prettier' was not found 문제를 처리하는 과정에서 에러를 잡으려고 여러가지를 시도하던 중 처리를 하지 못했던 것 같습니다. 죄송합니다

2022-06-01 16:31 UTC, KIMMIKSIK commented on src/components/secondContentBox.jsx
> +  font-size: 16px;
GlobalStyle은 잘 작동하고 있습니다. 일정등록 폼 다시 디자인에 맞춰서 pr올릴 예정이오니 조금만 기다려 주시면 감사하겠습니다.

2022-06-01 16:38 UTC, KIMMIKSIK commented on src/components/thirdContentBox.jsx
> +          <Input placeholder="학번을 입력해주세요" />
네 좋은 리뷰 감사드립니다. 형님 덕분에 문제점을 많이 알아가네요 수정하겠습니다!!

2022-06-01 16:41 UTC, KIMMIKSIK commented on package.json
> +    "eslint-plugin-prettier": "^4.0.0",
위에서 말씀드린 definition for rule 'prettier/prettier' was not found라는 에러를 계속 경험하였습니다. eslint-plugin-prettier를 설치하고나서 이 부분을 해결할 수 있었는데 이번주 동안 새로 작업하면서 왜 알람이 떴는지 다른 방법으로는 해결할 수 없는지 알아보고 말씀드리겠습니다!

2022-06-01 16:45 UTC, KIMMIKSIK commented on src/components/firstContentBox.jsx
> +`;
이 부분은 제가 Groupbox라는 div안에 들어가는 하위 태그들에 스타일을 넣기 위해서 작성한 코드들인데 괜찮으시다면 이 부분은 다음 회의 때  수정 내용을 가지고 가면서 함께 말씀드리겠습니다.

2022-06-03 07:32 UTC, KimGaeun0806 approved these changes

2022-06-06 07:14 UTC, wjdgml3834 approved these changes
여러번 수정사항이 있으셨을텐데, 고생많으셨습니다. 
혹시 context api를 사용하셨는데 구체적으로 어떤 것을 위해 사용하셨는지 궁금합니다!
그리고 다음부터 가능하시면 회의 때 얘기 했던 것 처럼 커밋 메세지 컨벤션 따라주시면 조금 더 좋을 듯 합니다.
[커밋 메세지 컨벤션](https://overcome-the-limits.tistory.com/entry/%ED%98%91%EC%97%85-%ED%98%91%EC%97%85%EC%9D%84-%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8-git-%EC%BB%A4%EB%B0%8B%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

2022-06-06 09:25 UTC, ordidxzero approved these changes

2022-06-06 10:27 UTC, closed without merging